Complete docs for api and readme
Zecrey-Labs/enc-collision-service pull request #3
Opened 2021-12-16 11:27 UTC by tt-loveslife

Complete readme and api docs

2021-12-16 11:52 UTC, tyGavinZJU requested changes

2021-12-16 11:52 UTC, tyGavinZJU commented on Collision_API.md
> +> 解密碰撞表，因为解密时间是线性的，如果数很大，需要的时间将非常长，通过后台设计碰撞表，将解密时间降低至常量级。
In English

2021-12-16 12:09 UTC, tt-loveslife commented on Collision_API.md
> +> 解密碰撞表，因为解密时间是线性的，如果数很大，需要的时间将非常长，通过后台设计碰撞表，将解密时间降低至常量级。
Solved in commit 7222e61

2021-12-20 06:24 UTC, tyGavinZJU requested changes

2021-12-20 06:24 UTC, tyGavinZJU commented on README.md
> +# 最好持久化到环境变量
In English

2021-12-21 04:56 UTC, tt-loveslife commented on README.md
> +# 最好持久化到环境变量
Solved in commit e15e7d2

2022-02-17 04:59 UTC, tyGavinZJU requested changes

2022-02-17 04:59 UTC, tyGavinZJU commented on README.md
> +Windows下开发环境使用`Goland + WSL2 + Docker`体验较好
delete it

2022-02-17 04:59 UTC, tyGavinZJU commented on README.md
> +docker run --name collision -p 5432:5432 -e POSTGRES_DB=crypto -e POSTGRES_USER=root -e POSTGRES_PASSWORD=123456  -d ghcr.io/tt-loveslife/collisiondatabase:0.0.2
hide db info

2022-02-17 06:48 UTC, tyGavinZJU approved these changes

2022-02-17 06:48 UTC, merged